runtime: python27
api_version: 1
threadsafe: true

handlers:
# - url: /favicon\.ico
#   static_files: favicon.ico
#   upload: favicon\.ico

- url: /stylesheets
  static_dir: stylesheets
- url: /js
  static_dir: js
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest